name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  config:
    required: false
    description: 'the configuration file'
runs:
  using: 'node12'
  main: 'dist/index.js'
