name: 'protector'
description: 'protector enforces branch protection as code just the way we are working in modern software development.'
author: 'Marc "m19c" Binder <marcandrebinder+github@gmail.com>'
inputs:
  config:
    required: false
    description: 'the configuration file'
  token:
    required: false
    description: 'the github access token'
runs:
  using: 'node12'
  main: 'dist/release/index.js'
